"""app/ui/custom_emoji_mapping.py — Semantic keys and default fallback unicode emojis."""

from __future__ import annotations

# Semantic UI keys mapped to fallback unicode emojis for all bot functions (Zero hardcoded custom_emoji_ids).
CUSTOM_EMOJI_MAP: dict[str, str] = {
    "VIP": "💎",
    "ADMIN": "👮",
    "USERS": "👥",
    "STATS": "📊",
    "SETTINGS": "⚙️",
    "BROADCAST": "📢",
    "PAYMENT": "💳",
    "SUPPORT": "🎧",
    "FORCE_JOIN": "📌",
    "SUCCESS": "✅",
    "DANGER": "🔴",
    "BACK": "⬅️",
    "SEARCH": "🔍",
    "SECURITY": "🔐",
    "CANCEL": "❌",
    "CONVERT": "🔄",
    "SPLIT": "✂️",
    "MERGE": "🔀",
    "VIEW": "👁️",
    "EDIT": "✏️",
    "ADD": "➕",
    "MESSAGE": "📩",
    "BAN": "🚫",
    "UNBAN": "🟢",
    "SPAM": "🛡️",
    "OTP": "📨",
    "CONTACTS": "📋",
    "EXPORT": "📝",
    "UNLOCK": "🔓",
    "RESET": "♻️",
    "REFRESH": "🔄",
    "DELETE": "🗑️",
    "FLAG_EN": "🇬🇧",
    "FLAG_FA": "🇮🇷",
    "FLAG_RU": "🇷🇺",
    "FLAG_AR": "🇸🇦",
    "FLAG_ZH": "🇨🇳",
    "FLAG_UZ": "🇺🇿",
    "FLAG_BN": "🇧🇩",
    "FLAG_HI": "🇮🇳",
    "FLAG_UR": "🇵🇰",
}
